from pathlib import Path
from html import escape

ROOT = Path('/mnt/data/bibliotecaDRFPostgreSQL')

lessons = [
{
'id':'inicio','group':'Inicio','n':'01','title':'DRF + PostgreSQL desde cero','subtitle':'Construye una API académica completa sin saltos','easy':'En este curso vas a construir una API. Una API no es una página con botones: es un servicio que recibe peticiones HTTP y responde datos, normalmente JSON.','analogy':'Piensa en una ventanilla: el cliente entrega una solicitud, la API valida qué se pide, consulta o modifica la base de datos y devuelve una respuesta.','why':'Primero debes conocer el resultado final y entender que todas las lecciones modifican el mismo proyecto.','files':['api_academia/README.md'],'tree':'api_academia/\n└── README.md   ← editas ahora','steps':['Crea una carpeta llamada api_academia.','Dentro crea README.md.','Escribe el objetivo: gestionar programas y estudiantes mediante una API REST.','No empieces un proyecto nuevo en cada capítulo.'],'code':'# API Academia\n\nProyecto progresivo con Django REST Framework + PostgreSQL.\n\nRecursos principales:\n- programas\n- estudiantes\n\nObjetivo: crear, listar, consultar, actualizar y eliminar datos mediante HTTP y JSON.','test':'Al terminar debes poder explicar qué recursos tendrá la API y que todo crecerá dentro de api_academia/.','activity':'Dibuja en una hoja el recorrido: Cliente → API → PostgreSQL → API → JSON.'
},
{
'id':'web-http','group':'Fundamentos Web y API','n':'02','title':'Cliente, servidor, HTTP y API','subtitle':'Antes de DRF entiende el camino de una petición','easy':'Un cliente puede ser un navegador, una app móvil, JavaScript o Postman. El servidor ejecuta Django. HTTP define cómo se envían solicitudes y respuestas.','analogy':'Un cliente hace un pedido; el servidor lo recibe; la API decide qué hacer; la base de datos guarda o busca la información.','why':'DRF trabaja encima de HTTP. Si entiendes petición y respuesta, GET, POST y códigos de estado dejan de parecer comandos aislados.','files':['docs/http.md'],'tree':'api_academia/\n├── README.md\n└── docs/\n    └── http.md   ← nuevo','steps':['Crea docs/http.md.','Anota las partes de una URL: protocolo, host, puerto y ruta.','Relaciona GET con consultar y POST con crear.','Relaciona respuesta con status + headers + body.'],'code':'GET http://127.0.0.1:8000/api/estudiantes/\n\nSolicitud\n├── Método: GET\n├── Ruta: /api/estudiantes/\n└── Headers\n\nRespuesta\n├── Status: 200 OK\n├── Headers\n└── Body: JSON','test':'Debes distinguir cliente, servidor, petición y respuesta.','activity':'Clasifica estas acciones por método: listar estudiantes, crear estudiante, editar correo y eliminar estudiante.'
},
{
'id':'rest-json','group':'Fundamentos Web y API','n':'03','title':'REST, recursos y JSON','subtitle':'Cómo diseñar una API entendible','easy':'REST organiza la API alrededor de recursos. En nuestro caso los recursos son programas y estudiantes. JSON es el formato de datos que intercambiaremos.','analogy':'En una biblioteca física tienes colecciones: libros, autores, préstamos. En una API tienes rutas para recursos: /libros/, /autores/, /prestamos/.','why':'Antes de programar conviene definir qué nombres y rutas tendrá la API.','files':['docs/diseno_api.md'],'tree':'api_academia/\n└── docs/\n    ├── http.md\n    └── diseno_api.md   ← nuevo','steps':['Define los recursos programa y estudiante.','Usa sustantivos en plural para las rutas.','Diferencia colección /estudiantes/ de elemento /estudiantes/7/.','Escribe un JSON de ejemplo.'],'code':'GET    /api/estudiantes/      # lista\nPOST   /api/estudiantes/      # crea\nGET    /api/estudiantes/7/    # detalle\nPUT    /api/estudiantes/7/    # reemplaza\nPATCH  /api/estudiantes/7/    # modifica parcialmente\nDELETE /api/estudiantes/7/    # elimina\n\n{\n  "id": 7,\n  "nombre": "Ana",\n  "correo": "ana@example.com",\n  "programa": 1\n}','test':'Debes saber qué cambia entre /estudiantes/ y /estudiantes/7/.','activity':'Diseña rutas REST para materias y docentes sin escribir Python todavía.'
},
{
'id':'bd-conceptos','group':'Base de datos desde cero','n':'04','title':'Base de datos, tabla, fila y columna','subtitle':'Las piezas mínimas de una base de datos relacional','easy':'Una base de datos organiza información. Una tabla agrupa datos del mismo tipo. Una fila representa un registro y una columna representa una característica.','analogy':'Una hoja de cálculo ayuda a imaginarlo: las columnas son propiedades y cada fila es una entidad. La diferencia es que una base relacional aplica reglas, tipos y relaciones con mayor rigor.','why':'Los modelos de Django terminarán convirtiéndose en tablas de PostgreSQL.','files':['docs/modelo_datos.md'],'tree':'api_academia/\n└── docs/\n    └── modelo_datos.md   ← nuevo','steps':['Dibuja la tabla programa.','Dibuja la tabla estudiante.','Marca id como identificador.','Evita mezclar varios conceptos en una sola columna.'],'code':'TABLA programa\n+----+--------------------------+\n| id | nombre                   |\n+----+--------------------------+\n|  1 | Ingeniería de Sistemas  |\n|  2 | Diseño Gráfico          |\n+----+--------------------------+\n\nTABLA estudiante\n+----+--------+-------------------+-------------+\n| id | nombre | correo            | programa_id |\n+----+--------+-------------------+-------------+\n|  7 | Ana    | ana@example.com   | 1           |\n+----+--------+-------------------+-------------+','test':'Debes poder señalar tabla, fila, columna y valor en el ejemplo.','activity':'Modela una tabla materia con al menos cinco columnas y escribe qué representa cada una.'
},
{
'id':'pk-fk','group':'Base de datos desde cero','n':'05','title':'Clave primaria y clave foránea','subtitle':'Cómo se conectan las tablas','easy':'La clave primaria identifica una fila de forma única. La clave foránea guarda el identificador de otra tabla y crea una relación.','analogy':'El número de documento identifica a una persona; el código de un programa permite saber a qué programa pertenece un estudiante sin repetir todo el nombre del programa en cada fila.','why':'La relación Programa → Estudiante será la primera relación real del proyecto.','files':['docs/modelo_datos.md'],'tree':'programa                 estudiante\n--------                 ----------\nid (PK)  <────────────── programa_id (FK)\nnombre                   id (PK)\n                         nombre\n                         correo','steps':['Marca programa.id como PK.','Agrega estudiante.programa_id.','Haz que programa_id apunte a programa.id.','Entiende que muchos estudiantes pueden pertenecer a un programa.'],'code':'-- Idea SQL\nCREATE TABLE programa (\n  id BIGINT PRIMARY KEY,\n  nombre VARCHAR(120) NOT NULL\n);\n\nCREATE TABLE estudiante (\n  id BIGINT PRIMARY KEY,\n  nombre VARCHAR(120) NOT NULL,\n  programa_id BIGINT NOT NULL,\n  CONSTRAINT fk_estudiante_programa\n    FOREIGN KEY (programa_id) REFERENCES programa(id)\n);','test':'Debes explicar por qué programa_id no guarda el nombre completo del programa.','activity':'Agrega una tabla materia y decide dónde pondrías una FK si cada materia pertenece a un programa.'
},
{
'id':'relaciones','group':'Base de datos desde cero','n':'06','title':'Relaciones 1:1, 1:N y N:M','subtitle':'Aprende a elegir la relación correcta','easy':'Una relación 1:1 conecta un registro con uno. 1:N conecta uno con muchos. N:M conecta muchos con muchos mediante una tabla intermedia.','analogy':'Persona-pasaporte puede ser 1:1; programa-estudiantes es 1:N; estudiantes-materias suele ser N:M.','why':'Elegir mal una relación causa duplicación o limita el sistema.','files':['docs/modelo_datos.md'],'tree':'Programa 1 ───── N Estudiante\nEstudiante N ─── N Materia\n             │\n             └─ Matrícula (tabla puente)','steps':['Identifica Programa → Estudiante como 1:N.','Imagina Estudiante ↔ Materia como N:M.','Crea conceptualmente la tabla Matricula.','No implementes Matricula todavía: primero entiende el patrón.'],'code':'matricula\n+----+---------------+------------+\n| id | estudiante_id | materia_id |\n+----+---------------+------------+\n|  1 | 7             | 3          |\n|  2 | 7             | 5          |\n+----+---------------+------------+','test':'Debes reconocer cuándo necesitas una tabla intermedia.','activity':'Clasifica: usuario-perfil, departamento-empleados, estudiantes-cursos.'
},
{
'id':'tipos-restricciones','group':'Base de datos desde cero','n':'07','title':'Tipos, NULL, UNIQUE, DEFAULT y CHECK','subtitle':'Reglas que protegen la calidad de los datos','easy':'Los tipos indican qué puede guardar una columna. Las restricciones impiden datos inválidos o repetidos.','analogy':'Un formulario puede decir “solo números” o “correo obligatorio”. La base de datos también puede imponer reglas, incluso si la aplicación comete un error.','why':'Correo será único, nombre obligatorio y estado tendrá un valor por defecto.','files':['docs/modelo_datos.md'],'tree':'estudiante\n├── id BIGINT PK\n├── nombre VARCHAR NOT NULL\n├── correo VARCHAR UNIQUE NOT NULL\n├── activo BOOLEAN DEFAULT TRUE\n└── programa_id BIGINT FK','steps':['Marca nombre como obligatorio.','Marca correo como único.','Agrega activo con valor inicial true.','Distingue NULL de cadena vacía.'],'code':'CREATE TABLE estudiante (\n  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  nombre VARCHAR(120) NOT NULL,\n  correo VARCHAR(254) NOT NULL UNIQUE,\n  activo BOOLEAN NOT NULL DEFAULT TRUE,\n  programa_id BIGINT NOT NULL REFERENCES programa(id)\n);','test':'Debes explicar qué error evita UNIQUE en correo.','activity':'Propón una restricción CHECK para una nota entre 0 y 5.'
},
{
'id':'normalizacion','group':'Base de datos desde cero','n':'08','title':'Normalización sin complicarse','subtitle':'Evita repetir información innecesaria','easy':'Normalizar es organizar los datos para no repetir lo mismo muchas veces y para evitar inconsistencias. Para empezar basta con entender 1FN, 2FN y 3FN a nivel práctico.','analogy':'Si guardas el nombre del programa en cada estudiante, un cambio de nombre obliga a actualizar cientos de filas. Separar Programa evita ese problema.','why':'Nuestro diseño separa Programa y Estudiante porque representan entidades distintas.','files':['docs/modelo_datos.md'],'tree':'ANTES\nestudiante(id, nombre, programa_nombre, programa_facultad)\n\nDESPUÉS\nprograma(id, nombre, facultad)\nestudiante(id, nombre, programa_id)','steps':['Busca datos repetidos.','Separa entidades que tienen vida propia.','Usa PK para identificar.','Usa FK para relacionar en vez de copiar datos.'],'code':'-- Evita\n(1, \'Ana\', \'Sistemas\', \'Ingenierías\')\n(2, \'Luis\', \'Sistemas\', \'Ingenierías\')\n\n-- Mejor\nprograma:   (10, \'Sistemas\', \'Ingenierías\')\nestudiante: (1, \'Ana\', 10)\nestudiante: (2, \'Luis\', 10)','test':'Debes detectar qué dato se repetía innecesariamente.','activity':'Revisa una tabla ficticia pedido(cliente_nombre, cliente_telefono, producto_nombre, cantidad) y separa posibles entidades.'
},
{
'id':'sql-basico','group':'SQL básico','n':'09','title':'SQL: CREATE, INSERT y SELECT','subtitle':'Habla directamente con PostgreSQL','easy':'SQL es el lenguaje con el que puedes definir y consultar datos. Django ORM generará SQL por ti, pero entender lo básico te ayuda a depurar.','analogy':'El ORM es como un traductor: tú escribes Python y Django produce SQL. Saber algo de SQL te permite entender qué termina ejecutándose.','why':'Antes de usar ORM practicarás operaciones simples en PostgreSQL.','files':['sql/01_basico.sql'],'tree':'api_academia/\n└── sql/\n    └── 01_basico.sql   ← nuevo','steps':['Crea una tabla de práctica.','Inserta dos filas.','Consulta todas.','Consulta solo algunas columnas.'],'code':'CREATE TABLE practica_programa (\n  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  nombre VARCHAR(120) NOT NULL\n);\n\nINSERT INTO practica_programa(nombre) VALUES (\'Sistemas\');\nINSERT INTO practica_programa(nombre) VALUES (\'Diseño\');\n\nSELECT * FROM practica_programa;\nSELECT id, nombre FROM practica_programa;','test':'La consulta debe devolver las dos filas insertadas.','activity':'Agrega un tercer programa y consulta únicamente su nombre.'
},
{
'id':'sql-filtros','group':'SQL básico','n':'10','title':'WHERE, ORDER BY, UPDATE y DELETE','subtitle':'Filtrar y modificar datos con cuidado','easy':'WHERE selecciona filas. ORDER BY ordena. UPDATE modifica. DELETE elimina. Sin WHERE, UPDATE o DELETE pueden afectar muchas filas.','analogy':'WHERE es como decir “solo los estudiantes activos”. Si olvidas esa condición, la instrucción puede aplicarse a todos.','why':'Estos conceptos equivaldrán luego a filter(), order_by(), save() y delete() del ORM.','files':['sql/02_crud.sql'],'tree':'sql/\n├── 01_basico.sql\n└── 02_crud.sql   ← nuevo','steps':['Filtra por nombre.','Ordena alfabéticamente.','Actualiza una fila usando WHERE.','Elimina una fila específica usando WHERE.'],'code':'SELECT * FROM practica_programa\nWHERE nombre = \'Sistemas\';\n\nSELECT * FROM practica_programa\nORDER BY nombre ASC;\n\nUPDATE practica_programa\nSET nombre = \'Ingeniería de Sistemas\'\nWHERE id = 1;\n\nDELETE FROM practica_programa\nWHERE id = 2;','test':'Antes de ejecutar DELETE debes poder decir exactamente qué fila se eliminará.','activity':'Escribe un UPDATE que cambie un nombre solo cuando id sea 3.'
},
{
'id':'sql-join','group':'SQL básico','n':'11','title':'JOIN y GROUP BY','subtitle':'Consulta información relacionada','easy':'JOIN combina filas de tablas relacionadas. GROUP BY reúne filas para calcular totales, conteos o promedios.','analogy':'La FK guarda solo un id. JOIN te permite volver a mostrar datos legibles de ambas tablas.','why':'Luego usarás select_related() y agregaciones del ORM.','files':['sql/03_join.sql'],'tree':'programa 1 ───── N estudiante\n         JOIN por programa_id','steps':['Relaciona estudiante.programa_id con programa.id.','Selecciona nombre del estudiante y nombre del programa.','Cuenta cuántos estudiantes hay por programa.','Entiende que INNER JOIN muestra coincidencias existentes.'],'code':'SELECT e.nombre AS estudiante, p.nombre AS programa\nFROM estudiante e\nINNER JOIN programa p ON p.id = e.programa_id;\n\nSELECT p.nombre, COUNT(e.id) AS total\nFROM programa p\nLEFT JOIN estudiante e ON e.programa_id = p.id\nGROUP BY p.id, p.nombre\nORDER BY p.nombre;','test':'Debes explicar para qué sirve ON p.id = e.programa_id.','activity':'Escribe conceptualmente un JOIN entre materia y programa.'
},
{
'id':'postgres-instalar','group':'PostgreSQL','n':'12','title':'Instalar PostgreSQL y reconocer sus herramientas','subtitle':'Servidor, puerto, usuario, base y cliente','easy':'PostgreSQL es el motor de base de datos. El servidor suele escuchar en el puerto 5432. Puedes conectarte con psql, pgAdmin u otro cliente.','analogy':'PostgreSQL es el almacén; psql y pgAdmin son diferentes puertas para administrar ese almacén.','why':'Django se conectará al servidor PostgreSQL, no a un archivo local de SQLite.','files':['docs/postgresql.md'],'tree':'PostgreSQL Server\n├── puerto 5432\n├── rol postgres\n└── bases de datos','steps':['Instala una versión soportada de PostgreSQL.','Recuerda la contraseña del rol administrador.','Verifica que el servicio esté iniciado.','Prueba la conexión con psql o pgAdmin.'],'code':'psql --version\n\n# Entrar con el usuario administrador\npsql -U postgres -h localhost -p 5432\n\n# Dentro de psql\nSELECT version();','test':'Debes obtener la versión del servidor sin error de conexión.','activity':'Identifica en tu instalación: host, puerto, usuario y nombre de una base de datos.'
},
{
'id':'postgres-comandos','group':'PostgreSQL','n':'13','title':'psql: comandos esenciales','subtitle':'Muévete por PostgreSQL sin miedo','easy':'psql tiene comandos propios que empiezan por barra invertida. No son SQL, pero sirven para explorar.','analogy':'SQL consulta datos; los comandos de psql ayudan a navegar el entorno.','why':'Cuando algo falle podrás comprobar si la base, tablas y usuario existen.','files':['docs/postgresql.md'],'tree':'psql\n├── \\l      bases\n├── \\c      conectar\n├── \\dt     tablas\n├── \\d      describir\n└── \\q      salir','steps':['Lista bases con \\l.','Conéctate con \\c nombre_db.','Lista tablas con \\dt.','Describe una tabla con \\d nombre.'],'code':'\\l\n\\c api_academia_db\n\\dt\n\\d academia_estudiante\n\\q','test':'Debes diferenciar \\dt de SELECT * FROM tabla;.','activity':'Crea una chuleta personal con 6 comandos de psql y su función.'
},
{
'id':'postgres-db-user','group':'PostgreSQL','n':'14','title':'Crear usuario y base del proyecto','subtitle':'No uses el superusuario para tu aplicación','easy':'La aplicación debe conectarse con un rol propio y una base propia. Así limitas permisos y separas proyectos.','analogy':'No entregarías la llave maestra del edificio a cada aplicación; creas una llave específica para su espacio.','why':'api_academia tendrá un rol y una base exclusivos.','files':['sql/00_crear_bd.sql','.env.example'],'tree':'PostgreSQL\n├── role: api_academia_user\n└── db:   api_academia_db','steps':['Entra como administrador.','Crea el rol con LOGIN.','Crea la base y asigna el propietario.','Verifica conexión con el nuevo rol.'],'code':"CREATE ROLE api_academia_user\nWITH LOGIN PASSWORD 'cambia_esta_clave';\n\nCREATE DATABASE api_academia_db\nOWNER api_academia_user;\n\n-- Desde terminal\npsql -U api_academia_user -h localhost -d api_academia_db",'test':'El nuevo usuario debe poder conectarse a api_academia_db.','activity':'Explica por qué conviene que cada proyecto tenga su propio usuario de BD.'
},
{
'id':'entorno','group':'Django + DRF','n':'15','title':'Python, entorno virtual e instalación','subtitle':'Prepara un entorno limpio','easy':'Un entorno virtual aísla las dependencias del proyecto. Instalaremos Django, DRF, psycopg y python-dotenv.','analogy':'Es una caja de herramientas exclusiva para este proyecto; evita mezclar versiones con otros proyectos.','why':'A partir de aquí comienza el proyecto ejecutable.','files':['requirements.txt','.venv/'],'tree':'api_academia/\n├── .venv/        ← entorno local\n└── requirements.txt','steps':['Comprueba Python 3.12 o superior.','Crea .venv.','Activa el entorno.','Actualiza pip e instala dependencias.'],'code':'python --version\npython -m venv .venv\n\n# Windows PowerShell\n.\\.venv\\Scripts\\Activate.ps1\n\n# Linux/macOS\nsource .venv/bin/activate\n\npython -m pip install --upgrade pip\npip install "Django>=6.1,<6.2" "djangorestframework>=3.18,<3.19" "psycopg[binary]>=3.1.12" "python-dotenv>=1.0"\npip freeze > requirements.txt','test':'python -m django --version debe mostrar Django 6.1.x.','activity':'Desactiva y vuelve a activar el entorno para comprobar que entiendes dónde están las dependencias.'
},
{
'id':'crear-proyecto','group':'Django + DRF','n':'16','title':'Crear el proyecto y la app','subtitle':'config contiene configuración; academia contiene el dominio','easy':'El proyecto Django guarda la configuración general. Una app agrupa una parte funcional del sistema.','analogy':'El proyecto es el edificio; la app academia es un área especializada dentro del edificio.','why':'Separaremos configuración de reglas del dominio académico.','files':['manage.py','config/','academia/'],'tree':'api_academia/\n├── manage.py\n├── config/\n│   ├── settings.py\n│   ├── urls.py\n│   └── ...\n└── academia/\n    ├── models.py\n    ├── views.py\n    └── ...','steps':['Ejecuta startproject en la carpeta actual.','Crea la app academia.','Revisa los archivos generados.','No borres los archivos __init__.py.'],'code':'django-admin startproject config .\npython manage.py startapp academia\n\n# Verifica\npython manage.py check','test':'python manage.py check debe terminar sin errores.','activity':'Explica con tus palabras la diferencia entre config/ y academia/.'
},
{
'id':'settings-postgres','group':'Django + DRF','n':'17','title':'Conectar Django con PostgreSQL','subtitle':'settings.py + variables de entorno','easy':'Django necesita saber qué motor, base, usuario, contraseña, host y puerto debe usar.','analogy':'Son los datos de dirección y acceso para llegar al servidor PostgreSQL.','why':'Desde esta lección, las migraciones crearán tablas en PostgreSQL.','files':['config/settings.py','.env','.env.example','.gitignore'],'tree':'api_academia/\n├── .env              ← NO subir\n├── .env.example      ← sí subir\n├── .gitignore\n└── config/\n    └── settings.py   ← editas','steps':['Crea .env con tus datos reales.','Carga .env con python-dotenv.','Cambia DATABASES a django.db.backends.postgresql.','Agrega rest_framework y academia a INSTALLED_APPS.','Ignora .env en Git.'],'code':"# .env\nDB_NAME=api_academia_db\nDB_USER=api_academia_user\nDB_PASSWORD=cambia_esta_clave\nDB_HOST=localhost\nDB_PORT=5432\n\n# config/settings.py\nimport os\nfrom dotenv import load_dotenv\nload_dotenv(BASE_DIR / '.env')\n\nINSTALLED_APPS += [\n    'rest_framework',\n    'academia',\n]\n\nDATABASES = {\n    'default': {\n        'ENGINE': 'django.db.backends.postgresql',\n        'NAME': os.getenv('DB_NAME'),\n        'USER': os.getenv('DB_USER'),\n        'PASSWORD': os.getenv('DB_PASSWORD'),\n        'HOST': os.getenv('DB_HOST', 'localhost'),\n        'PORT': os.getenv('DB_PORT', '5432'),\n    }\n}",'test':'python manage.py check debe funcionar; si la conexión está mal, migrate mostrará el problema.','activity':'Cambia temporalmente DB_NAME por un nombre inexistente, observa el error y luego restáuralo.'
},
{
'id':'modelo-programa','group':'Modelos y ORM','n':'18','title':'Primer modelo: Programa','subtitle':'De una clase Python a una tabla','easy':'Un Model de Django describe una entidad y sus campos. Una migración traduce cambios del modelo a operaciones de base de datos.','analogy':'models.py es el plano; la migración es la orden de construcción; PostgreSQL contiene la estructura ya construida.','why':'Programa será la tabla padre de Estudiante.','files':['academia/models.py'],'tree':'academia/\n└── models.py   ← Programa','steps':['Importa models.','Crea Programa.','Usa CharField para nombre.','Agrega __str__ para mostrarlo mejor en admin y consola.'],'code':"from django.db import models\n\nclass Programa(models.Model):\n    nombre = models.CharField(max_length=120, unique=True)\n    activo = models.BooleanField(default=True)\n\n    class Meta:\n        ordering = ['nombre']\n\n    def __str__(self):\n        return self.nombre",'test':'python manage.py makemigrations debe detectar la creación de Programa.','activity':'Agrega un campo codigo de máximo 20 caracteres y hazlo único.'
},
{
'id':'modelo-estudiante','group':'Modelos y ORM','n':'19','title':'Modelo Estudiante y ForeignKey','subtitle':'Implementa la relación 1:N','easy':'ForeignKey representa una relación muchos-a-uno. Cada estudiante apunta a un programa.','analogy':'El estudiante guarda la referencia al programa, no una copia completa de todos sus datos.','why':'Aquí el concepto de FK de la base de datos se convierte en código Django.','files':['academia/models.py'],'tree':'Programa 1 ───── N Estudiante\n                  ├── nombre\n                  ├── correo UNIQUE\n                  ├── activo\n                  └── programa FK','steps':['Crea Estudiante debajo de Programa.','Usa EmailField(unique=True).','Crea ForeignKey a Programa.','Usa on_delete=PROTECT para impedir borrar un programa con estudiantes.'],'code':"class Estudiante(models.Model):\n    nombre = models.CharField(max_length=120)\n    correo = models.EmailField(unique=True)\n    activo = models.BooleanField(default=True)\n    programa = models.ForeignKey(\n        Programa,\n        on_delete=models.PROTECT,\n        related_name='estudiantes',\n    )\n\n    class Meta:\n        ordering = ['nombre']\n\n    def __str__(self):\n        return f'{self.nombre} - {self.correo}'",'test':'Debes poder explicar qué hace on_delete=PROTECT y related_name.','activity':'Prueba mentalmente qué cambiaría con CASCADE y por qué puede ser peligroso.'
},
{
'id':'migraciones','group':'Modelos y ORM','n':'20','title':'Migraciones: makemigrations y migrate','subtitle':'Lleva los modelos a PostgreSQL','easy':'makemigrations crea archivos que describen cambios. migrate ejecuta esos cambios en la base.','analogy':'Primero redactas la obra que quieres hacer; después la ejecutas.','why':'Hasta ahora los modelos existen en Python, pero PostgreSQL aún necesita sus tablas.','files':['academia/migrations/0001_initial.py'],'tree':'academia/\n└── migrations/\n    └── 0001_initial.py   ← generado','steps':['Ejecuta makemigrations.','Revisa el archivo generado.','Ejecuta migrate.','Abre psql y verifica tablas academia_programa y academia_estudiante.'],'code':'python manage.py makemigrations\npython manage.py migrate\npython manage.py showmigrations\n\n# psql\n\\dt\n\\d academia_estudiante','test':'\\dt debe mostrar las tablas creadas por Django.','activity':'Agrega un campo fecha_creacion con auto_now_add=True y genera una segunda migración.'
},
{
'id':'orm','group':'Modelos y ORM','n':'21','title':'ORM: crear, consultar, filtrar y actualizar','subtitle':'Python que termina convirtiéndose en SQL','easy':'El ORM permite trabajar con objetos Python en lugar de escribir SQL para cada operación.','analogy':'Es el traductor entre tu código Python y PostgreSQL.','why':'Las views de la API usarán QuerySets para obtener datos.','files':['Django shell'],'tree':'Python ORM\n   ↓\nDjango\n   ↓\nSQL\n   ↓\nPostgreSQL','steps':['Abre shell.','Crea un Programa.','Crea un Estudiante relacionado.','Filtra activos.','Mira query para observar el SQL aproximado.'],'code':"python manage.py shell\n\nfrom academia.models import Programa, Estudiante\n\np = Programa.objects.create(nombre='Ingeniería de Sistemas')\nEstudiante.objects.create(\n    nombre='Ana Torres',\n    correo='ana@example.com',\n    programa=p,\n)\n\nqs = Estudiante.objects.filter(activo=True)\nprint(qs)\nprint(qs.query)", 'test':'Estudiante.objects.count() debe devolver al menos 1 después de crear el ejemplo.','activity':'Filtra estudiantes cuyo nombre contenga ana sin importar mayúsculas usando nombre__icontains.'
},
{
'id':'select-related','group':'Modelos y ORM','n':'22','title':'Consultas relacionadas: select_related','subtitle':'Evita consultas innecesarias','easy':'Cuando vas a usar la FK programa de muchos estudiantes, select_related puede traer los datos relacionados en una sola consulta JOIN.','analogy':'En vez de ir al almacén una vez por cada estudiante, traes de una vez la información relacionada que necesitas.','why':'Es una optimización sencilla y visible en nuestro ViewSet.','files':['academia/views.py'],'tree':'Estudiante.objects\n└── select_related(\'programa\')\n    └── SQL JOIN','steps':['Compara un queryset normal.','Agrega select_related(programa).','Inspecciona query.','Entiende que aplica bien a ForeignKey y OneToOne.'],'code':"qs = Estudiante.objects.select_related('programa').all()\n\nfor estudiante in qs:\n    print(estudiante.nombre, estudiante.programa.nombre)\n\nprint(qs.query)", 'test':'Debes saber por qué select_related se usa para programa y no para una relación ManyToMany genérica.','activity':'Investiga conceptualmente para qué serviría prefetch_related en una N:M.'
},
{
'id':'serializers','group':'Django REST Framework','n':'23','title':'Serializer: de modelo a JSON','subtitle':'La pieza que valida y transforma datos','easy':'Un serializer convierte objetos Django a tipos que pueden representarse como JSON y también valida datos recibidos antes de crear o actualizar modelos.','analogy':'Es un traductor y un control de calidad al mismo tiempo.','why':'Sin serializer la API no sabe cómo exponer ni validar un Estudiante de forma cómoda.','files':['academia/serializers.py'],'tree':'academia/\n├── models.py\n└── serializers.py   ← nuevo','steps':['Crea serializers.py.','Crea ProgramaSerializer.','Crea EstudianteSerializer.','Incluye los campos que quieres exponer.'],'code':"from rest_framework import serializers\nfrom .models import Programa, Estudiante\n\nclass ProgramaSerializer(serializers.ModelSerializer):\n    class Meta:\n        model = Programa\n        fields = ['id', 'nombre', 'activo']\n\nclass EstudianteSerializer(serializers.ModelSerializer):\n    programa_nombre = serializers.CharField(\n        source='programa.nombre',\n        read_only=True,\n    )\n\n    class Meta:\n        model = Estudiante\n        fields = [\n            'id', 'nombre', 'correo', 'activo',\n            'programa', 'programa_nombre',\n        ]",'test':'Debes entender por qué programa se escribe y programa_nombre es solo lectura.','activity':'Agrega un campo solo lectura llamado estado_texto que devuelva Activo o Inactivo usando SerializerMethodField.'
},
{
'id':'api-view','group':'Django REST Framework','n':'24','title':'Tu primera vista de API con @api_view','subtitle':'GET sencillo antes de automatizar CRUD','easy':'@api_view convierte una función en una vista de DRF y te da Request, Response, negociación de contenido y manejo de métodos.','analogy':'Primero construiremos una puerta manual para entender qué ocurre antes de usar ViewSets.','why':'Si saltas directamente a ModelViewSet, el framework puede parecer magia.','files':['academia/views.py','academia/urls.py','config/urls.py'],'tree':'GET /api/saludo/\n      ↓\nacademia.urls\n      ↓\nviews.saludo\n      ↓\nResponse JSON','steps':['Crea saludo en views.py.','Crea academia/urls.py.','Incluye las URLs en config/urls.py.','Inicia runserver y abre /api/saludo/.'],'code':"# academia/views.py\nfrom rest_framework.decorators import api_view\nfrom rest_framework.response import Response\n\n@api_view(['GET'])\ndef saludo(request):\n    return Response({\n        'mensaje': 'API Academia funcionando'\n    })\n\n# academia/urls.py\nfrom django.urls import path\nfrom .views import saludo\n\nurlpatterns = [\n    path('saludo/', saludo),\n]\n\n# config/urls.py\nfrom django.contrib import admin\nfrom django.urls import include, path\n\nurlpatterns = [\n    path('admin/', admin.site.urls),\n    path('api/', include('academia.urls')),\n]",'test':'GET http://127.0.0.1:8000/api/saludo/ debe devolver JSON y 200.','activity':'Crea /api/info/ que devuelva nombre del proyecto y versión de la API.'
},
{
'id':'list-create','group':'Django REST Framework','n':'25','title':'Listar y crear estudiantes manualmente','subtitle':'Entiende GET, POST, validación y status','easy':'Con una función puedes manejar varios métodos. En GET serializas un queryset; en POST validas request.data y guardas.','analogy':'GET mira el inventario; POST entrega datos nuevos para crear una fila.','why':'Este paso hace visible lo que luego ModelViewSet automatizará.','files':['academia/views.py','academia/urls.py'],'tree':'GET/POST /api/estudiantes-manual/\n      ↓\nrequest.method\n      ↓\nSerializer\n      ↓\nORM / PostgreSQL','steps':['Agrega el endpoint manual.','En GET usa many=True.','En POST pasa request.data al serializer.','Usa is_valid(raise_exception=True).','Devuelve 201 al crear.'],'code':"from rest_framework import status\nfrom .models import Estudiante\nfrom .serializers import EstudianteSerializer\n\n@api_view(['GET', 'POST'])\ndef estudiantes_manual(request):\n    if request.method == 'GET':\n        qs = Estudiante.objects.select_related('programa').all()\n        return Response(EstudianteSerializer(qs, many=True).data)\n\n    serializer = EstudianteSerializer(data=request.data)\n    serializer.is_valid(raise_exception=True)\n    serializer.save()\n    return Response(serializer.data, status=status.HTTP_201_CREATED)", 'test':'Envía POST válido y luego GET: el nuevo estudiante debe aparecer.','activity':'Envía un correo repetido y observa el error generado por unique=True.'
},
{
'id':'viewset-router','group':'Django REST Framework','n':'26','title':'ModelViewSet + Router','subtitle':'CRUD completo con poco código, pero ahora entendiendo qué automatiza','easy':'ModelViewSet reúne list, create, retrieve, update, partial_update y destroy. Un Router genera las rutas REST estándar.','analogy':'Después de construir una puerta manual, usas un sistema modular que instala las puertas estándar por ti.','why':'Será la estructura final de nuestra API.','files':['academia/views.py','academia/urls.py'],'tree':'DefaultRouter\n├── /programas/\n├── /programas/{id}/\n├── /estudiantes/\n└── /estudiantes/{id}/','steps':['Crea ProgramaViewSet.','Crea EstudianteViewSet.','Usa select_related en estudiantes.','Registra ambos en DefaultRouter.','Quita o conserva las rutas manuales solo para aprendizaje.'],'code':"# academia/views.py\nfrom rest_framework import viewsets\nfrom .models import Programa, Estudiante\nfrom .serializers import ProgramaSerializer, EstudianteSerializer\n\nclass ProgramaViewSet(viewsets.ModelViewSet):\n    queryset = Programa.objects.all()\n    serializer_class = ProgramaSerializer\n\nclass EstudianteViewSet(viewsets.ModelViewSet):\n    queryset = Estudiante.objects.select_related('programa').all()\n    serializer_class = EstudianteSerializer\n\n# academia/urls.py\nfrom rest_framework.routers import DefaultRouter\nfrom .views import ProgramaViewSet, EstudianteViewSet\n\nrouter = DefaultRouter()\nrouter.register('programas', ProgramaViewSet)\nrouter.register('estudiantes', EstudianteViewSet)\n\nurlpatterns = router.urls",'test':'Abre /api/ y revisa las rutas generadas por el Browsable API.','activity':'Agrega un recurso Materia usando el mismo patrón Model + Serializer + ViewSet + Router.'
},
{
'id':'crud-rutas','group':'Django REST Framework','n':'27','title':'CRUD completo y rutas exactas','subtitle':'Qué método usar en cada operación','easy':'CRUD significa Create, Read, Update y Delete. REST asigna estas acciones a métodos HTTP y rutas.','analogy':'Una colección usa la ruta plural; un elemento concreto agrega su id.','why':'Los estudiantes deben saber qué URL probar y qué respuesta esperar.','files':['academia/urls.py'],'tree':'/api/estudiantes/\n├── GET    lista\n└── POST   crea\n\n/api/estudiantes/{id}/\n├── GET    detalle\n├── PUT    reemplaza\n├── PATCH  modifica\n└── DELETE elimina','steps':['Prueba GET colección.','Prueba POST colección.','Prueba GET detalle.','Prueba PATCH cambiando solo activo.','Prueba DELETE sobre un registro de prueba.'],'code':'# Crear\nPOST /api/estudiantes/\n{\n  "nombre": "Luis Pérez",\n  "correo": "luis@example.com",\n  "activo": true,\n  "programa": 1\n}\n\n# Actualizar parcialmente\nPATCH /api/estudiantes/2/\n{\n  "activo": false\n}','test':'Debes poder elegir el método correcto sin mirar una tabla.','activity':'Escribe cinco casos de prueba manuales para CRUD, incluyendo al menos dos errores.'
},
{
'id':'status-errors','group':'API bien diseñada','n':'28','title':'Códigos HTTP y errores','subtitle':'Una API también comunica con su status','easy':'El status indica el resultado general: 200 consulta correcta, 201 creación, 204 eliminación, 400 datos inválidos, 401 sin autenticar, 403 sin permiso, 404 no encontrado.','analogy':'El body explica detalles; el status es una señal corta y estándar del resultado.','why':'Un frontend o app móvil suele tomar decisiones según estos códigos.','files':['docs/http.md'],'tree':'Respuesta HTTP\n├── status\n├── headers\n└── body JSON','steps':['Prueba crear un estudiante correcto.','Prueba correo inválido.','Consulta un id inexistente.','Elimina un registro y observa 204.'],'code':'201 Created\n{ "id": 8, "nombre": "Luis", ... }\n\n400 Bad Request\n{ "correo": ["Enter a valid email address."] }\n\n404 Not Found\n{ "detail": "No Estudiante matches the given query." }','test':'Debes explicar por qué un error de validación normalmente es 400 y no 500.','activity':'Relaciona estos casos con status: login requerido, permiso insuficiente, registro inexistente, creación correcta.'
},
{
'id':'validacion','group':'API bien diseñada','n':'29','title':'Validación personalizada','subtitle':'Reglas del negocio en el serializer','easy':'Los campos validan formato y restricciones, pero a veces el negocio necesita reglas adicionales. Puedes usar validate_campo o validate.','analogy':'EmailField sabe qué parece un correo; tu regla de negocio decide, por ejemplo, que un estudiante inactivo no puede cambiarse a cierto estado sin condición.','why':'No toda regla puede expresarse solo con el tipo de columna.','files':['academia/serializers.py'],'tree':'request.data\n   ↓\nSerializer\n├── validación de campos\n├── validate_<campo>\n└── validate\n   ↓\nserializer.save()','steps':['Agrega validate_nombre.','Limpia espacios.','Impide nombres demasiado cortos.','Prueba respuestas 400.'],'code':"class EstudianteSerializer(serializers.ModelSerializer):\n    # ... Meta y campos ...\n\n    def validate_nombre(self, value):\n        value = value.strip()\n        if len(value) < 3:\n            raise serializers.ValidationError(\n                'El nombre debe tener al menos 3 caracteres.'\n            )\n        return value",'test':'POST con nombre “Al” debe responder 400 con mensaje claro.','activity':'Crea una validación para impedir correos del dominio ejemplo-invalido.test.'
},
{
'id':'filtros','group':'API bien diseñada','n':'30','title':'Filtros simples por query params','subtitle':'?activo=true&programa=1','easy':'Un query parameter permite modificar una consulta sin crear una ruta nueva.','analogy':'La ruta sigue siendo estudiantes; los parámetros son filtros opcionales aplicados a la lista.','why':'Es un paso sencillo antes de introducir paquetes de filtrado adicionales.','files':['academia/views.py'],'tree':'GET /api/estudiantes/?activo=true&programa=1\n                             ↓\n                         get_queryset','steps':['Sobrescribe get_queryset.','Lee request.query_params.','Filtra solo si el parámetro llegó.','Mantén select_related.'],'code':"class EstudianteViewSet(viewsets.ModelViewSet):\n    serializer_class = EstudianteSerializer\n\n    def get_queryset(self):\n        qs = Estudiante.objects.select_related('programa').all()\n        activo = self.request.query_params.get('activo')\n        programa = self.request.query_params.get('programa')\n\n        if activo in {'true', 'false'}:\n            qs = qs.filter(activo=(activo == 'true'))\n        if programa:\n            qs = qs.filter(programa_id=programa)\n        return qs",'test':'GET /api/estudiantes/?activo=true debe devolver solo activos.','activity':'Agrega un parámetro nombre que filtre con nombre__icontains.'
},
{
'id':'paginacion','group':'API bien diseñada','n':'31','title':'Paginación','subtitle':'No envíes miles de filas en una sola respuesta','easy':'La paginación divide una colección grande en páginas. DRF puede configurarla globalmente.','analogy':'Como un libro: no cargas todas las páginas en la pantalla al mismo tiempo.','why':'Es una práctica básica cuando una tabla puede crecer.','files':['config/settings.py'],'tree':'GET /api/estudiantes/?page=2\n\n{\n  count, next, previous, results[]\n}','steps':['Agrega REST_FRAMEWORK.','Elige PageNumberPagination.','Configura PAGE_SIZE pequeño para practicar.','Crea varios estudiantes y cambia page.'],'code':"REST_FRAMEWORK = {\n    'DEFAULT_PAGINATION_CLASS':\n        'rest_framework.pagination.PageNumberPagination',\n    'PAGE_SIZE': 5,\n}", 'test':'La lista debe devolver count, next, previous y results.','activity':'Crea 12 registros de prueba y calcula cuántas páginas aparecen con PAGE_SIZE=5.'
},
{
'id':'auth','group':'Seguridad básica','n':'32','title':'Autenticación y permisos','subtitle':'Identidad no es lo mismo que autorización','easy':'Autenticación responde “¿quién eres?”. Permisos responden “¿puedes hacer esto?”. DRF evalúa autenticación antes de permisos.','analogy':'Mostrar tu identificación no significa automáticamente que puedas entrar a todas las salas.','why':'Una API real no debería permitir cualquier modificación anónima.','files':['config/settings.py'],'tree':'Request\n  ↓\nAuthentication → request.user\n  ↓\nPermissions\n  ↓\nView','steps':['Agrega SessionAuthentication para usar Browsable API.','Agrega BasicAuthentication solo para práctica local.','Configura IsAuthenticatedOrReadOnly.','Prueba GET anónimo y POST anónimo.'],'code':"REST_FRAMEWORK = {\n    'DEFAULT_AUTHENTICATION_CLASSES': [\n        'rest_framework.authentication.SessionAuthentication',\n        'rest_framework.authentication.BasicAuthentication',\n    ],\n    'DEFAULT_PERMISSION_CLASSES': [\n        'rest_framework.permissions.IsAuthenticatedOrReadOnly',\n    ],\n    'DEFAULT_PAGINATION_CLASS':\n        'rest_framework.pagination.PageNumberPagination',\n    'PAGE_SIZE': 5,\n}", 'test':'GET puede ser público y POST debe pedir autenticación.','activity':'Explica por qué BasicAuthentication solo debe usarse con HTTPS si sale de un entorno local.'
},
{
'id':'token','group':'Seguridad básica','n':'33','title':'TokenAuthentication de DRF','subtitle':'Una opción simple para clientes no basados en sesión','easy':'DRF incluye un sistema simple de tokens. El cliente envía Authorization: Token ... en cada petición.','analogy':'El login obtiene una credencial que luego acompaña cada solicitud.','why':'Es suficiente para enseñar la idea de autenticación por token antes de estudiar JWT u otros esquemas.','files':['config/settings.py','config/urls.py'],'tree':'POST /api-token-auth/\n   ↓ username/password\n{ token }\n   ↓\nAuthorization: Token abc123...','steps':['Agrega rest_framework.authtoken.','Ejecuta migrate.','Agrega TokenAuthentication.','Expón obtain_auth_token.','Crea un superusuario y solicita un token.'],'code':"# settings.py -> INSTALLED_APPS\n'rest_framework.authtoken',\n\n# REST_FRAMEWORK\n'DEFAULT_AUTHENTICATION_CLASSES': [\n    'rest_framework.authentication.TokenAuthentication',\n    'rest_framework.authentication.SessionAuthentication',\n],\n\n# config/urls.py\nfrom rest_framework.authtoken.views import obtain_auth_token\n\nurlpatterns += [\n    path('api-token-auth/', obtain_auth_token),\n]\n\n# Header\nAuthorization: Token TU_TOKEN",'test':'Una petición autenticada con token debe poder crear datos si los permisos lo permiten.','activity':'Compara en una tabla conceptual sesión vs token: dónde se guarda la credencial y quién suele usarla.'
},
{
'id':'proteger-delete','group':'Seguridad básica','n':'34','title':'Permisos por acción','subtitle':'Lectura para todos, escritura solo autenticados','easy':'Puedes cambiar permisos según la acción del ViewSet. La propiedad action indica si estás listando, creando, actualizando o eliminando.','analogy':'La sala de consulta puede ser pública; la zona de edición requiere credenciales.','why':'Te enseña que los permisos pueden ser globales o específicos por vista/acción.','files':['academia/views.py'],'tree':'ViewSet\n├── list/retrieve → AllowAny\n└── create/update/destroy → IsAuthenticated','steps':['Importa AllowAny e IsAuthenticated.','Sobrescribe get_permissions.','Permite list y retrieve sin login.','Exige autenticación para el resto.'],'code':"from rest_framework.permissions import AllowAny, IsAuthenticated\n\nclass EstudianteViewSet(viewsets.ModelViewSet):\n    # ...\n    def get_permissions(self):\n        if self.action in ['list', 'retrieve']:\n            classes = [AllowAny]\n        else:\n            classes = [IsAuthenticated]\n        return [permission() for permission in classes]",'test':'Prueba GET sin token y POST sin token; deben comportarse distinto.','activity':'Haz que DELETE requiera IsAdminUser y documenta el motivo.'
},
{
'id':'pruebas-manuales','group':'Pruebas','n':'35','title':'Probar con Browsable API y curl','subtitle':'No confíes en que “se ve bien”','easy':'Una API debe probar métodos, datos válidos, errores y permisos. DRF trae una interfaz navegable útil para aprender. curl permite reproducir peticiones desde terminal.','analogy':'Probar una API es intentar tanto el camino correcto como los caminos que deben fallar.','why':'Antes de automatizar tests necesitas saber qué comportamiento esperas.','files':['docs/pruebas.md'],'tree':'Cliente de prueba\n├── Browser DRF\n├── curl\n└── Postman/Insomnia (opcional)','steps':['Prueba GET lista.','Prueba POST válido.','Prueba POST inválido.','Prueba 404.','Prueba autenticación.'],'code':"curl http://127.0.0.1:8000/api/estudiantes/\n\ncurl -X POST http://127.0.0.1:8000/api/estudiantes/ \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Authorization: Token TU_TOKEN\" \\\n  -d '{\"nombre\":\"Carlos\",\"correo\":\"carlos@example.com\",\"programa\":1}'",'test':'Debes tener una lista de casos de prueba y resultados esperados.','activity':'Crea una tabla con 10 pruebas: método, URL, body, status esperado y resultado.'
},
{
'id':'tests','group':'Pruebas','n':'36','title':'Tests automáticos de API','subtitle':'APIClient y APITestCase','easy':'Un test automático prepara datos, ejecuta una petición y verifica el resultado. Puede repetirse después de cada cambio.','analogy':'En vez de revisar manualmente diez puertas después de cada modificación, un robot las prueba por ti.','why':'Protege el CRUD de regresiones y enseña a pensar en comportamiento.','files':['academia/tests.py'],'tree':'academia/\n└── tests.py   ← pruebas de API','steps':['Crea un programa en setUp.','Prueba GET de programas.','Prueba POST de estudiante inválido.','Ejecuta python manage.py test.'],'code':"from django.urls import reverse\nfrom rest_framework import status\nfrom rest_framework.test import APITestCase\nfrom .models import Programa\n\nclass ProgramaApiTests(APITestCase):\n    def setUp(self):\n        self.programa = Programa.objects.create(\n            nombre='Sistemas'\n        )\n\n    def test_listar_programas(self):\n        response = self.client.get('/api/programas/')\n        self.assertEqual(response.status_code, status.HTTP_200_OK)\n        self.assertEqual(len(response.data['results']), 1)", 'test':'python manage.py test debe terminar OK.','activity':'Agrega un test que verifique que no se puede repetir el nombre de un programa.'
},
{
'id':'transacciones','group':'Base de datos aplicada','n':'37','title':'Transacciones','subtitle':'Todo o nada cuando varias operaciones dependen entre sí','easy':'Una transacción agrupa operaciones. Si algo falla, puedes revertir el conjunto y evitar datos a medias.','analogy':'Una transferencia bancaria no debe descontar dinero de una cuenta si no logra abonarlo en la otra.','why':'Aunque nuestro CRUD simple no siempre lo necesita, es un concepto central de bases de datos.','files':['docs/base_datos_avanzando.md'],'tree':'transaction.atomic()\n├── operación A\n├── operación B\n└── error → rollback','steps':['Entiende commit y rollback.','Revisa transaction.atomic.','Identifica operaciones que deben ser indivisibles.','No agregues atomic sin necesidad a todo.'],'code':"from django.db import transaction\n\nwith transaction.atomic():\n    # ambas operaciones forman una unidad lógica\n    programa = Programa.objects.create(nombre='Nuevo')\n    Estudiante.objects.create(\n        nombre='Ana',\n        correo='ana2@example.com',\n        programa=programa,\n    )",'test':'Debes explicar qué significa “todo o nada”.','activity':'Propón un caso académico donde dos o más cambios deban ejecutarse dentro de la misma transacción.'
},
{
'id':'indices','group':'Base de datos aplicada','n':'38','title':'Índices y rendimiento básico','subtitle':'Más velocidad de lectura con un costo','easy':'Un índice puede acelerar búsquedas, pero ocupa espacio y hace que escrituras deban mantener ese índice. No se crea un índice para cada columna sin pensar.','analogy':'Es el índice de un libro: acelera encontrar temas, pero hay que mantenerlo cuando cambia el contenido.','why':'Correo unique ya genera una necesidad de búsqueda eficiente; otros filtros frecuentes pueden necesitar índices.','files':['academia/models.py'],'tree':'Consulta frecuente\n   ↓\n¿campo selectivo y usado en filtros?\n   ↓\nconsiderar índice','steps':['Identifica filtros frecuentes.','Recuerda que unique crea una restricción única respaldada por índice en PostgreSQL.','Usa db_index=True solo con motivo.','Mide antes de optimizar sistemas reales.'],'code':"class Estudiante(models.Model):\n    # ...\n    activo = models.BooleanField(default=True)\n    fecha_creacion = models.DateTimeField(auto_now_add=True, db_index=True)\n\n# luego\npython manage.py makemigrations\npython manage.py migrate",'test':'Debes saber por qué indexar un BooleanField por sí solo puede no ser útil en muchos escenarios.','activity':'Elige dos consultas del proyecto y razona qué columnas participan en filtros, ordenamientos y joins.'
},
{
'id':'admin','group':'Herramientas Django','n':'39','title':'Admin para inspeccionar datos','subtitle':'Una interfaz de administración, no el frontend de tu API','easy':'Django Admin ayuda a crear y revisar datos mientras desarrollas, pero no reemplaza los endpoints REST.','analogy':'Es un panel interno para administradores; la API es la interfaz programable que usan otros sistemas.','why':'Facilita comprobar relaciones y datos durante las prácticas.','files':['academia/admin.py'],'tree':'/admin/\n├── Programas\n└── Estudiantes','steps':['Registra modelos.','Crea superusuario.','Entra a /admin/.','Crea registros y confirma que aparecen en /api/.'],'code':"from django.contrib import admin\nfrom .models import Programa, Estudiante\n\n@admin.register(Programa)\nclass ProgramaAdmin(admin.ModelAdmin):\n    list_display = ('id', 'nombre', 'activo')\n    search_fields = ('nombre',)\n\n@admin.register(Estudiante)\nclass EstudianteAdmin(admin.ModelAdmin):\n    list_display = ('id', 'nombre', 'correo', 'programa', 'activo')\n    list_filter = ('activo', 'programa')\n    search_fields = ('nombre', 'correo')\n\n# terminal\npython manage.py createsuperuser",'test':'Un estudiante creado en admin debe verse al consultar la API.','activity':'Agrega filtros o búsquedas útiles para un administrador académico.'
},
{
'id':'proyecto-final','group':'Proyecto final','n':'40','title':'Proyecto final: API Academia','subtitle':'Checklist completo desde base de datos hasta pruebas','easy':'Ya tienes todas las piezas. El proyecto final consiste en reconstruirlas desde una carpeta vacía sin copiar todo de una vez.','analogy':'La guía fue el entrenamiento; ahora repites el proceso entendiendo por qué existe cada archivo.','why':'El aprendizaje se consolida cuando puedes construir el flujo completo en orden.','files':['todo el proyecto'],'tree':'api_academia/\n├── manage.py\n├── requirements.txt\n├── .env\n├── config/\n│   ├── settings.py\n│   └── urls.py\n└── academia/\n    ├── models.py\n    ├── serializers.py\n    ├── views.py\n    ├── urls.py\n    ├── admin.py\n    └── tests.py','steps':['Crea rol y base PostgreSQL.','Crea entorno e instala dependencias.','Crea proyecto y app.','Configura PostgreSQL.','Implementa modelos y migra.','Crea serializers.','Crea ViewSets y Router.','Agrega paginación, autenticación y permisos.','Carga datos.','Prueba CRUD y errores.','Ejecuta tests.'],'code':'RUTAS FINALES\n\nGET/POST        /api/programas/\nGET/PATCH/DELETE /api/programas/{id}/\n\nGET/POST        /api/estudiantes/\nGET/PATCH/DELETE /api/estudiantes/{id}/\n\nPOST             /api-token-auth/\nGET              /admin/','test':'El proyecto está completo cuando puede arrancar desde cero, conectarse a PostgreSQL y pasar sus pruebas.','activity':'Extiende el sistema con Materia y Matrícula para practicar una relación N:M real.'
},
{
'id':'deploy','group':'Cierre','n':'41','title':'Antes de producción','subtitle':'Variables, DEBUG, HTTPS, backup y servidor real','easy':'runserver es para desarrollo. En producción debes usar una configuración segura, servidor WSGI/ASGI apropiado, HTTPS, secretos fuera del repositorio y copias de seguridad.','analogy':'Que una casa esté lista para una maqueta no significa que ya cumpla todos los requisitos para vivir en ella.','why':'La guía no debe dejar la impresión de que runserver y una contraseña en Git son suficientes.','files':['.env','.gitignore','docs/produccion.md'],'tree':'Producción\n├── DEBUG=False\n├── ALLOWED_HOSTS\n├── secretos externos\n├── HTTPS\n├── servidor app\n├── PostgreSQL seguro\n└── backups','steps':['No subas .env.','Usa DEBUG=False.','Configura ALLOWED_HOSTS.','Usa HTTPS para autenticación.','Automatiza backups de PostgreSQL.','Separa settings según entorno en proyectos mayores.'],'code':'# ejemplo de respaldo manual\npg_dump -U api_academia_user -h localhost \\\n  -Fc api_academia_db > api_academia.backup\n\n# restauración a otra base\npg_restore -U api_academia_user -h localhost \\\n  -d api_academia_db_restaurada api_academia.backup','test':'Debes poder enumerar al menos cinco diferencias entre desarrollo y producción.','activity':'Crea un checklist de despliegue y marca qué elementos todavía faltan en tu proyecto.'
},
]

groups=[]
for l in lessons:
    if l['group'] not in groups: groups.append(l['group'])

nav=''
for g in groups:
    items=''.join(f'<a class="nav-link" href="#{l["id"]}" data-target="{l["id"]}"><span>{l["n"]}</span>{escape(l["title"])}</a>' for l in lessons if l['group']==g)
    nav += f'<div class="nav-group"><div class="nav-group-title">{escape(g)}</div>{items}</div>'

sections=[]
for l in lessons:
    filechips=''.join(f'<span class="file-chip">📄 {escape(f)}</span>' for f in l['files'])
    steps=''.join(f'<li><span class="stepnum">{i}</span><div>{escape(s)}</div></li>' for i,s in enumerate(l['steps'],1))
    section=f'''<section class="lesson" id="{l['id']}" data-title="{escape(l['title'].lower())}" data-group="{escape(l['group'].lower())}">
      <div class="lesson-kicker">{l['n']} · {escape(l['group'].upper())}</div>
      <h2>{escape(l['title'])}</h2>
      <p class="lead">{escape(l['subtitle'])}</p>
      <div class="lesson-actions"><button class="understand" data-lesson="{l['id']}">○ Pendiente</button><button class="bookmark" data-bookmark="{l['id']}">☆ Guardar</button></div>

      <div class="easy-grid">
        <div class="mini-card"><b>💡 En palabras simples</b><p>{escape(l['easy'])}</p></div>
        <div class="mini-card"><b>🏠 Ejemplo cotidiano</b><p>{escape(l['analogy'])}</p></div>
        <div class="mini-card"><b>🎯 ¿Por qué aquí?</b><p>{escape(l['why'])}</p></div>
      </div>

      <div class="project-box">
        <div class="box-title">🧩 APLÍCALO AL MISMO PROYECTO</div>
        <div class="file-row">{filechips}</div>
        <div class="project-grid">
          <div>
            <div class="subhead">📂 Estructura en esta lección</div>
            <pre class="tree"><code>{escape(l['tree'])}</code></pre>
          </div>
          <div>
            <div class="subhead">👣 Paso a paso</div>
            <ol class="steps">{steps}</ol>
          </div>
        </div>
      </div>

      <div class="code-wrap">
        <div class="code-head"><span>⌨ Código / comandos</span><button class="copy">Copiar</button></div>
        <pre><code>{escape(l['code'])}</code></pre>
      </div>

      <div class="check"><b>✅ COMPROBACIÓN</b><p>{escape(l['test'])}</p></div>
      <div class="activity"><b>🌟 ACTIVIDAD COMPLEMENTARIA</b><p>{escape(l['activity'])}</p><small>🟡 Para reforzar la lección. No es obligatorio para continuar.</small></div>
    </section>'''
    sections.append(section)

html=f'''<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DRF + PostgreSQL Academy · API desde cero</title>
<meta name="description" content="Guía progresiva de Django REST Framework con PostgreSQL y fundamentos de bases de datos.">
<style>
:root{{--bg:#071017;--panel:#0c1821;--panel2:#10212c;--text:#eaf2f6;--muted:#99acb8;--line:#1d3543;--accent:#7dd3fc;--green:#6ee7b7;--yellow:#fde68a;--red:#fca5a5;--shadow:0 12px 32px rgba(0,0,0,.22)}}
*{{box-sizing:border-box}} html{{scroll-behavior:smooth}} body{{margin:0;background:linear-gradient(135deg,#061018,#0a1721 45%,#071119);color:var(--text);font:15px/1.65 Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif}}
a{{color:inherit;text-decoration:none}} button,input{{font:inherit}}
.topbar{{height:64px;position:fixed;inset:0 0 auto 0;z-index:30;background:rgba(7,16,23,.9);backdrop-filter:blur(16px);border-bottom:1px solid var(--line);display:flex;align-items:center;gap:18px;padding:0 22px}}
.brand{{display:flex;align-items:center;gap:10px;font-weight:800;white-space:nowrap}} .logo{{width:34px;height:34px;border-radius:10px;background:linear-gradient(145deg,#4fc3f7,#6ee7b7);display:grid;place-items:center;color:#04202a;font-weight:900}}
.search{{flex:1;max-width:620px;margin:auto;position:relative}} .search input{{width:100%;background:#0b1a24;border:1px solid var(--line);color:var(--text);border-radius:12px;padding:10px 14px 10px 38px;outline:none}} .search:before{{content:'⌕';position:absolute;left:13px;top:6px;color:var(--muted);font-size:22px}}
.top-actions{{display:flex;gap:8px}} .iconbtn{{background:#0b1a24;border:1px solid var(--line);color:var(--text);border-radius:10px;padding:8px 11px;cursor:pointer}}
.sidebar{{position:fixed;top:64px;bottom:0;left:0;width:310px;overflow:auto;padding:18px 14px 80px;border-right:1px solid var(--line);background:#08131b;z-index:20}}
.progress-card{{padding:14px;border:1px solid var(--line);background:#0b1a24;border-radius:14px;margin-bottom:16px}} .progress-line{{height:8px;background:#102936;border-radius:999px;overflow:hidden;margin:8px 0}} .progress-fill{{height:100%;width:0;background:linear-gradient(90deg,#38bdf8,#6ee7b7)}} .progress-meta{{display:flex;justify-content:space-between;color:var(--muted);font-size:12px}}
.nav-group{{margin:14px 0}} .nav-group-title{{font-size:11px;letter-spacing:.12em;color:#6f8795;font-weight:800;text-transform:uppercase;margin:8px 9px}} .nav-link{{display:flex;gap:10px;align-items:center;padding:8px 10px;border-radius:9px;color:#adbec8;font-size:13px;margin:2px 0}} .nav-link span{{min-width:25px;color:#638095;font-size:11px}} .nav-link:hover,.nav-link.active{{background:#112532;color:#fff}} .nav-link.done{{color:#b9f4d8}} .nav-link.done:after{{content:'✓';margin-left:auto;color:var(--green)}}
.main{{margin-left:310px;padding-top:64px}} .hero{{max-width:1180px;margin:auto;padding:64px 42px 34px}} .eyebrow{{font-size:12px;letter-spacing:.14em;color:var(--green);font-weight:900}} h1{{font-size:clamp(38px,5.2vw,72px);line-height:1.02;margin:12px 0 18px;letter-spacing:-.04em}} .hero p{{color:#b8c7cf;font-size:18px;max-width:830px}} .badges{{display:flex;flex-wrap:wrap;gap:9px;margin:22px 0}} .badge{{border:1px solid var(--line);background:#0e202b;border-radius:999px;padding:7px 11px;color:#c8d6dd;font-size:12px}}
.roadmap{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:24px}} .road{{padding:14px;border:1px solid var(--line);border-radius:12px;background:rgba(14,32,43,.72)}} .road b{{display:block;color:var(--accent);margin-bottom:3px}} .road small{{color:var(--muted)}}
.reference{{margin-top:20px;border-left:3px solid var(--accent);background:#0d202c;padding:14px 16px;border-radius:0 12px 12px 0;color:#bed0da}}
.content{{max-width:1180px;margin:auto;padding:0 42px 100px}} .lesson{{scroll-margin-top:84px;border-top:1px solid var(--line);padding:58px 0 20px}} .lesson-kicker{{font-size:12px;letter-spacing:.13em;color:var(--green);font-weight:900}} h2{{font-size:clamp(28px,3.6vw,46px);line-height:1.1;margin:8px 0 6px;letter-spacing:-.025em}} .lead{{color:#9eb1bc;font-size:18px;margin-top:0}} .lesson-actions{{display:flex;gap:8px;margin:15px 0 22px}} .understand,.bookmark{{border:1px solid var(--line);background:#0d1d27;color:#cbd9df;border-radius:9px;padding:8px 12px;cursor:pointer}} .understand.on{{border-color:#2f8066;background:#0c2a22;color:#a7f3d0}} .bookmark.on{{border-color:#9a7c2d;color:#fde68a}}
.easy-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}} .mini-card{{border:1px solid var(--line);background:linear-gradient(160deg,#0c1a24,#0a171f);padding:18px;border-radius:14px}} .mini-card b{{font-size:12px;letter-spacing:.04em;color:#cce8f4}} .mini-card p{{color:#aebfc8;margin:8px 0 0}}
.project-box{{margin-top:18px;border:1px solid #22506a;background:#0a1a25;border-radius:16px;padding:20px}} .box-title{{font-size:12px;font-weight:900;letter-spacing:.1em;color:#7dd3fc}} .file-row{{display:flex;flex-wrap:wrap;gap:7px;margin:14px 0}} .file-chip{{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;border:1px solid #285168;background:#0c2634;border-radius:8px;padding:6px 8px;color:#bde9fb}} .project-grid{{display:grid;grid-template-columns:.9fr 1.1fr;gap:14px}} .subhead{{font-size:12px;font-weight:800;color:#c4d4dc;margin:8px 0}} .tree{{height:100%;min-height:180px}}
pre{{margin:0;background:#061117;border:1px solid #173444;border-radius:12px;padding:16px;overflow:auto;color:#d2e7ef;font:13px/1.58 ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre}} code{{font-family:inherit}} .steps{{list-style:none;padding:0;margin:0}} .steps li{{display:flex;gap:10px;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.05)}} .steps li:last-child{{border-bottom:0}} .stepnum{{display:grid;place-items:center;min-width:26px;height:26px;border-radius:7px;background:#14384b;color:#9bdfff;font-weight:800;font-size:12px}}
.code-wrap{{margin-top:14px;border:1px solid var(--line);border-radius:14px;overflow:hidden}} .code-head{{display:flex;justify-content:space-between;align-items:center;background:#0d202b;padding:9px 12px;color:#9fc1d1;font-size:12px;font-weight:700}} .copy{{border:1px solid #294b5c;background:#0a1720;color:#bad0db;border-radius:7px;padding:5px 9px;cursor:pointer}} .code-wrap pre{{border:0;border-radius:0;background:#050d12}}
.check{{margin-top:14px;padding:16px;border:1px solid #285745;background:#0b211b;border-radius:13px}} .check b{{color:#9ff2ca;font-size:12px}} .check p{{margin:6px 0 0;color:#b9d6c8}} .activity{{margin-top:12px;padding:16px;border:1px solid #755e1c;background:#28200b;border-radius:13px}} .activity b{{color:var(--yellow);font-size:12px}} .activity p{{margin:6px 0;color:#e7d9a8}} .activity small{{color:#a8955d}}
footer{{border-top:1px solid var(--line);padding:30px 42px;color:#758c99;max-width:1180px;margin:auto}}
.no-results{{display:none;margin:30px 0;padding:20px;border:1px solid var(--line);border-radius:12px;color:var(--muted)}}
@media(max-width:980px){{.sidebar{{transform:translateX(-100%);transition:.25s}} body.menu-open .sidebar{{transform:none}} .main{{margin-left:0}} .roadmap{{grid-template-columns:1fr 1fr}} .easy-grid,.project-grid{{grid-template-columns:1fr}} .top-actions .label{{display:none}}}}
@media(max-width:620px){{.topbar{{padding:0 10px;gap:8px}} .brand strong{{display:none}} .hero,.content{{padding-left:18px;padding-right:18px}} .hero{{padding-top:38px}} .roadmap{{grid-template-columns:1fr}} .search input{{font-size:13px}} h1{{font-size:40px}}}}
body.light{{--bg:#f4f7f8;--panel:#fff;--panel2:#fff;--text:#14242d;--muted:#60727c;--line:#d8e1e5;--accent:#0369a1;--green:#047857;--yellow:#a16207;--shadow:0 12px 32px rgba(17,24,39,.08);background:#f4f7f8}} body.light .topbar,body.light .sidebar{{background:rgba(249,251,252,.95)}} body.light .sidebar{{background:#f8fafb}} body.light .progress-card,body.light .nav-link:hover,body.light .nav-link.active,body.light .mini-card,body.light .project-box,body.light .code-head,body.light .search input,body.light .iconbtn{{background:#fff}} body.light pre,body.light .code-wrap pre{{background:#10212a;color:#e7f5fa}} body.light .check{{background:#edf9f3}} body.light .activity{{background:#fff9df}} body.light .hero p,body.light .lead,body.light .mini-card p{{color:#526771}}
</style>
</head>
<body>
<header class="topbar">
  <button class="iconbtn" id="menuBtn" aria-label="Menú">☰</button>
  <a class="brand" href="#inicio"><span class="logo">API</span><strong>DRF + PostgreSQL Academy</strong></a>
  <div class="search"><input id="search" placeholder="Buscar: serializers, JOIN, migraciones..." aria-label="Buscar"></div>
  <div class="top-actions"><button class="iconbtn" id="themeBtn">◐ <span class="label">Tema</span></button></div>
</header>
<aside class="sidebar">
  <div class="progress-card"><b>Progreso del curso</b><div class="progress-line"><div class="progress-fill" id="progressFill"></div></div><div class="progress-meta"><span id="progressText">0%</span><span id="progressCount">0/{len(lessons)}</span></div></div>
  <nav>{nav}</nav>
</aside>
<main class="main">
  <section class="hero">
    <div class="eyebrow">DJANGO REST FRAMEWORK · POSTGRESQL · BASES DE DATOS</div>
    <h1>De cero a una API REST conectada a PostgreSQL</h1>
    <p>Ruta progresiva para estudiantes: primero entiende HTTP, REST y bases de datos; después instala PostgreSQL, modela relaciones, conecta Django, aprende ORM, serializers, ViewSets, autenticación, pruebas y termina con un CRUD completo.</p>
    <div class="badges"><span class="badge">Django 6.1</span><span class="badge">DRF 3.18.x</span><span class="badge">Python 3.12+</span><span class="badge">PostgreSQL 15+ · recomendado 18.x</span><span class="badge">Proyecto progresivo: api_academia</span></div>
    <div class="roadmap">
      <div class="road"><b>1 · Entiende</b><small>HTTP, REST, JSON y conceptos de BD.</small></div>
      <div class="road"><b>2 · Modela</b><small>PK, FK, relaciones, SQL y PostgreSQL.</small></div>
      <div class="road"><b>3 · Construye</b><small>Django, ORM, serializers, ViewSets y Router.</small></div>
      <div class="road"><b>4 · Comprueba</b><small>CRUD, seguridad, tests y proyecto final.</small></div>
    </div>
    <div class="reference"><b>Referencia técnica actualizada a septiembre de 2026.</b> DRF 3.18 añadió soporte para Django 6.1; Django 6.1 soporta PostgreSQL 15+ y recomienda psycopg 3; PostgreSQL 18 es la rama estable actual. El curso evita “magia”: antes de ModelViewSet construye una vista manual para que se entienda el flujo.</div>
  </section>
  <div class="content">
    <div class="no-results" id="noResults">No encontré capítulos con ese texto.</div>
    {''.join(sections)}
  </div>
  <footer>DRF + PostgreSQL Academy · Proyecto didáctico progresivo · Guarda el progreso en este navegador.</footer>
</main>
<script>
const lessonIds={list(map(lambda l:l['id'],lessons))!r};
const done=new Set(JSON.parse(localStorage.getItem('drfDone')||'[]'));
const marks=new Set(JSON.parse(localStorage.getItem('drfMarks')||'[]'));
function save(){{localStorage.setItem('drfDone',JSON.stringify([...done]));localStorage.setItem('drfMarks',JSON.stringify([...marks]));updateProgress()}}
function updateProgress(){{
  const pct=Math.round(done.size/lessonIds.length*100);
  document.getElementById('progressFill').style.width=pct+'%';
  document.getElementById('progressText').textContent=pct+'%';
  document.getElementById('progressCount').textContent=done.size+'/'+lessonIds.length;
  document.querySelectorAll('.understand').forEach(b=>{{const on=done.has(b.dataset.lesson);b.classList.toggle('on',on);b.textContent=on?'✓ Entendido':'○ Pendiente'}});
  document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('done',done.has(a.dataset.target)));
  document.querySelectorAll('.bookmark').forEach(b=>{{const on=marks.has(b.dataset.bookmark);b.classList.toggle('on',on);b.textContent=on?'★ Guardado':'☆ Guardar'}});
}}
document.addEventListener('click',e=>{{
  const u=e.target.closest('.understand'); if(u){{done.has(u.dataset.lesson)?done.delete(u.dataset.lesson):done.add(u.dataset.lesson);save()}}
  const b=e.target.closest('.bookmark'); if(b){{marks.has(b.dataset.bookmark)?marks.delete(b.dataset.bookmark):marks.add(b.dataset.bookmark);save()}}
  const c=e.target.closest('.copy'); if(c){{const t=c.closest('.code-wrap').querySelector('code').innerText;navigator.clipboard.writeText(t);c.textContent='Copiado ✓';setTimeout(()=>c.textContent='Copiar',1200)}}
  if(e.target.closest('.nav-link')) document.body.classList.remove('menu-open');
}});
const search=document.getElementById('search');
search.addEventListener('input',()=>{{const q=search.value.trim().toLowerCase();let visible=0;document.querySelectorAll('.lesson').forEach(s=>{{const ok=!q||s.innerText.toLowerCase().includes(q);s.style.display=ok?'':'none';if(ok)visible++}});document.getElementById('noResults').style.display=visible?'none':'block'}});
document.getElementById('themeBtn').onclick=()=>{{document.body.classList.toggle('light');localStorage.setItem('drfTheme',document.body.classList.contains('light')?'light':'dark')}};
if(localStorage.getItem('drfTheme')==='light')document.body.classList.add('light');
document.getElementById('menuBtn').onclick=()=>document.body.classList.toggle('menu-open');
const obs=new IntersectionObserver(entries=>{{entries.forEach(x=>{{if(x.isIntersecting){{document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.target===x.target.id))}}}})}},{{rootMargin:'-25% 0px -65% 0px'}});document.querySelectorAll('.lesson').forEach(s=>obs.observe(s));
updateProgress();
</script>
</body></html>'''
(ROOT/'index.html').write_text(html,encoding='utf-8')
print('created', ROOT/'index.html', 'bytes', len(html.encode('utf-8')))
